# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
# Uncomment the lines below to configure your website in a second language.
es:
  languageCode: es-mx
  contentDir: content/es
     title: Titulo español ----
 params:
 description: Site description in Chinese...
  menu:
    main:
      - name: Yo
        url: '#about'
        weight: 1

en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en


