# Navigation Links
#   Cada enlace lleva a su propia página dentro de content/es/.

main:
  - name: Inicio
    url: /
    weight: 10
  - name: Sobre Nosotros
    url: /sobre-nosotros/
    weight: 20
  - name: Donatello
    url: /donatello/
    weight: 30
  - name: HORU
    url: /horu/
    weight: 40
  - name: Competiciones
    url: /competiciones/
    weight: 50
  - name: Eventos
    url: /eventos/
    weight: 60
  #- name: Nuestro Equipo
   # url: /equipo/
    #weight: 70
  #- name: Patrocinadores
    #url: /patrocinadores/
    #weight: 80
  - name: Reclutamiento
    url: /recruitment/
    weight: 90
  - name: Contacto
    url: /contacto/
    weight: 100
